// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    const isDemo =
      typeof window !== "undefined" && localStorage.getItem("fos_demo_mode") === "true";
    const isPlaceholder =
      !import.meta.env["VITE_SUPABASE_URL"] ||
      import.meta.env["VITE_SUPABASE_URL"].includes("placeholder");
    const token =
      data.session?.access_token || (isDemo || isPlaceholder ? "demo_token" : undefined);
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
